// Code generated by hand for the probe. DO NOT EDIT.

package probe

// Generated carries a default that would be reported anywhere else, and stays silent here because the
// file is generated.
type Generated struct {
	Endpoint string `env-default:"https://api.test.example.com"`
}
